### ISSUE TITLE
Having trouble using IR RC5 protocol for S905 Socs

### ISSUE THREAD

**Issue by NizarAloui** [150balbes/Amlogic_S905-u-boot#3]
I think this is due to the fact that the Remote IR RC5 protocol does not exists in the configs file.

Could you please add it ?

**Comment by 150balbes** [comment]
I'll see what I can do.

**Comment by NizarAloui** [comment]
Thanks

**Comment by 150balbes** [comment]
You can try to change this option.

https://github.com/150balbes/Amlogic_S905-u-boot/blob/master/include/configs/gxb_p200_v1.h#L67

**Comment by NizarAloui** [comment]
Thanks for the tip, the hing is this flag `CONFIG_IR_REMOTE_USE_PROTOCOL` is only for these protocols: `0:nec  1:duokan  2:Toshiba 3:rca 4:rcmm` No RC5 specified, I could also see in [scp_remote.c](https://github.com/150balbes/Amlogic_S905-u-boot/blob/master/arch/arm/cpu/armv8/gxb/firmware/scp_task/scp_remote.c) that the regesiters were only configured for these protocols:
```
static const reg_remote *remoteregsTab[] = {
	RDECODEMODE_NEC,
	RDECODEMODE_DUOKAN,
	RDECODEMODE_TOSHIBA,
	RDECODEMODE_RCA,
	RDECODEMODE_RCMM,
	RDECODEMODE_RC6,
};
```
So no RC5. I have tried to make a reg config for the RC5:
```
static const reg_remote RDECODEMODE_RC5[] = {
        { AO_MF_IR_DEC_LDR_ACTIVE ,  0            },
        { AO_MF_IR_DEC_LDR_IDLE   ,  0            },
        { AO_MF_IR_DEC_LDR_REPEAT ,  0            },
        { AO_MF_IR_DEC_BIT_0      ,  0            },
        { AO_MF_IR_DEC_REG0       ,  ((3 << 28) | (0x1644 << 12) | 0x13)},
        { AO_MF_IR_DEC_STATUS     ,  (1 << 30)    },
        { AO_MF_IR_DEC_REG1       ,  ((1 << 15) | (13 << 8))},
        /*bit[0-3]: RC5; bit[8]: MSB first mode; bit[11]: compare frame method*/
        { AO_MF_IR_DEC_REG2       ,  ((1 << 13) | (1 << 11) | (1 << 8) | 0x7)},
        /*Half bit for RC5 format: 888.89us*/ 
        { AO_MF_IR_DEC_DURATN2    ,  ((49 << 16) | (40 << 0))  },
        /*RC5 typically 1777.78us for whole bit*/
        { AO_MF_IR_DEC_DURATN3    ,  ((94 << 16) | (83 << 0))  },
        { AO_MF_IR_DEC_REG3       ,  0                   },
        {CONFIG_END, 0}
};
```

So I may need your help to confirm whether or not the above reg config is correct ?
Thanks,

**Comment by 150balbes** [comment]
I'm not an expert on remotes. You can add the necessary patches, assemble the new u-boot.bin.sd.bin, burn it on the SD card, disable the regular u-boot in eMMC and check the operation of your new u-boot when run from external media without the risk to brick.

**Comment by NizarAloui** [comment]
Ok I wanted to use **meson-ir** driver and plug it on **Lirc**, because it handles the RC5, so I don't need to configure registers for **meson-remote**, it will send the RAW data to the **meson-ir**. 
Each time I change the `mesongxl.dtsi` and rerun **./compile.sh**, the modification I made are disappear and replaced by the original one, even if I specify to not clean before rebuild. 
Is there any thing I'am doing wrong ?
Do I need to reburn the` u-boot.bin.sd.bin`, or I just install the `linux-u-boot-amlogic-s905x_5.34_arm64.deb` file generated on my running SD system and reboot ?

**Comment by NizarAloui** [comment]
I have figure out how to integrate the RC5. We can close the ticket.
