### ISSUE TITLE
How to change DDR clock

### ISSUE THREAD

**Issue by nvl1109** [150balbes/Amlogic_S905-u-boot#5]
Hello,

For Odroid C2, we can change DDR clock following https://forum.odroid.com/viewtopic.php?f=135&t=23540.
But for S905 based board (using your u-boot), do you have any idea to change DDR clock? Thanks.

**Comment by 7134956** [comment]
https://github.com/150balbes/Amlogic_S905-u-boot/blob/6087dffc05e02bc03d6de3026ccab5123ad46e52/include/configs/gxb_p200_v1.h#L249

**Comment by nvl1109** [comment]
Thanks. That's right. I have updated this before, but my mistake is forget to re-compile acs.bin, that's why the change is not applied. Thanks.
